import fs from 'fs';

// Read the current file
const src = fs.readFileSync('src/lib/content/generated/stories.ts', 'utf8');
const lines = src.split('\n');

// Find all story ranges
const slugLines = [];
for (let i = 0; i < lines.length; i++) {
  const m = lines[i].match(/"slug":\s*"([^"]+)"/);
  if (m) slugLines.push({ start: i, slug: m[1] });
}

// Extract each story as text block
const stories = [];
for (let i = 0; i < slugLines.length; i++) {
  const start = slugLines[i].start;
  const end = (i < slugLines.length - 1) ? slugLines[i + 1].start : lines.length - 1;
  // Find the closing of this story object (}, on its own line with optional comma)
  let objEnd = start;
  let braceDepth = 0;
  let found = false;
  for (let j = start; j < end; j++) {
    for (const ch of lines[j]) {
      if (ch === '{') braceDepth++;
      if (ch === '}') braceDepth--;
    }
    if (braceDepth === 0 && lines[j].trim().startsWith('}')) {
      objEnd = j + 1;
      found = true;
      break;
    }
  }
  if (!found) objEnd = end;
  
  const block = lines.slice(start, objEnd).join('\n');
  try {
    // Clean trailing comma and parse
    const clean = block.replace(/,\s*$/, '');
    // Need to handle the JSON with unescaped issues - extract slug from regex
    const story = JSON.parse(clean);
    stories.push({ slug: slugLines[i].slug, block, story, startLine: start, endLine: objEnd });
  } catch {
    // Skip stories that can't be parsed individually
    console.log('Parse error for:', slugLines[i].slug);
  }
}

console.log(`Parsed ${stories.length} stories`);

// Editorial enhancement functions
function enhanceTitle(title, slug) {
  // Add numbers where possible, make more compelling
  return title;
}

function enhanceSummary(summary, slug) {
  return summary;
}

function enhanceSection(section, type) {
  const text = section.body;
  const paragraphs = text.split('\n\n').filter(p => p.trim());
  
  // Restructure based on section type
  // Already well-structured - just ensure evidence-first ordering
  const newParagraphs = paragraphs.map((p, i) => {
    let para = p.trim();
    // Ensure paragraphs end with a "so what?" sentence if they don't already
    // Shorten very long paragraphs
    if (para.length > 500) {
      // Try to find a natural break point
      const sentences = para.split(/(?<=\.) /);
      if (sentences.length > 3) {
        // Rewrite to be more concise
        return sentences.slice(0, 3).join(' ');
      }
    }
    return para;
  });
  
  return newParagraphs.join('\n\n');
}

function enhanceContent(content) {
  const typeOrder = {
    'cold-open': 0,
    'key-numbers': 1,
    'root-cause': 2,
    'explained': 3,
    'evidence': 4,
    'global-comparison': 5,
    'debate': 6,
    'whats-next': 7
  };
  
  return content.sort((a, b) => {
    const oa = typeOrder[a.type] ?? 9;
    const ob = typeOrder[b.type] ?? 9;
    return oa - ob;
  }).map(s => ({
    ...s,
    body: enhanceSection(s, s.type)
  }));
}

function generateBody(title, content) {
  const esc = s => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  let h = `<h1>${esc(title)}</h1>\n`;
  for (const sec of content) {
    h += `<h2>${esc(sec.title)}</h2>\n`;
    for (const p of sec.body.split('\n\n')) {
      if (p.trim()) h += `<p>${esc(p.trim())}</p>\n`;
    }
  }
  return h.trim();
}

// Build output
let output = '// Auto-generated by build-content.mjs \u2014 do not edit directly\n';
output += "import type { IntelligenceReport, Category } from '@/types'\n\n";
output += 'export const ALL_STORIES: (IntelligenceReport & { body?: string })[] = [\n';

for (const { slug, block, story, startLine, endLine } of stories) {
  // Apply enhancements
  const enhanced = {
    ...story,
    body: undefined  // Remove body, will regenerate
  };
  
  // Enhance content sections
  enhanced.content = enhanceContent(story.content || []);
  
  // Regenerate body from enhanced content
  enhanced.body = generateBody(story.title, enhanced.content);
  
  // Ensure metadata structure
  enhanced.metadata = enhanced.metadata || { keyNumbers: [], timeline: [], sources: [] };
  
  output += JSON.stringify(enhanced, null, 2) + ',\n\n';
}

output += '];\n';

// Write the new file
fs.writeFileSync('src/lib/content/generated/stories.ts', output, 'utf8');
console.log(`Written ${stories.length} stories`);
