/**
 * THE BREAKDOWN OS — Phase 5: Visual Asset Generator
 *
 * Generates visual asset specifications for a story:
 *   - Hero image prompt
 *   - Supporting images
 *   - SVG chart data
 *   - Infographic ideas
 *   - Video suggestions
 *
 * Usage:
 *   node scripts/ai/visuals.mjs --slug <slug>
 *   node scripts/ai/visuals.mjs --topic "..." --content "article text"
 *
 * Requires OPENAI_API_KEY in .env at project root.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline';
import { stdin, stdout } from 'node:process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..', '..');

import { callOpenAI, requireApiKey, loadAgent, slugify } from './lib.mjs';

async function main() {
  const args = {};
  for (let i = 2; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const val = process.argv[i + 1];
      if (val && !val.startsWith('--')) { args[key] = val; i++; }
      else { args[key] = true; }
    }
  }

  requireApiKey();
  console.log('\n=== Phase 5 — Visual Asset Generator ===\n');

  let slug = args.slug || args.s;
  let topic = args.topic || args.t;
  let content = args.content;

  if (!slug && !topic) {
    const rl = createInterface({ input: stdin, output: stdout });
    topic = await new Promise(resolve => rl.question('Story topic: ', answer => { rl.close(); resolve(answer); }));
    slug = slugify(topic);
  }
  if (!slug) slug = slugify(topic || 'untitled');
  if (!topic) topic = slug;

  const storyDir = join(PROJECT_ROOT, 'stories', slug);
  const htmlPath = join(storyDir, `${slug}.html`);

  if (!content) {
    if (existsSync(htmlPath)) content = readFileSync(htmlPath, 'utf-8');
    else if (existsSync(join(storyDir, `${slug}.md`))) content = readFileSync(join(storyDir, `${slug}.md`), 'utf-8');
  }

  console.log(`  Topic: ${topic}`);
  console.log(`  Slug:  ${slug}\n`);
  console.log('Generating visual asset specifications...\n');

  const agent = loadAgent('visuals');
  const result = await callOpenAI(agent,
    `Story: ${topic}\n\nContent:\n${content || 'No content available. Generate standard visual specs.'}`,
    4096
  );

  if (!existsSync(storyDir)) mkdirSync(storyDir, { recursive: true });

  // Save as visuals.md and also extract SVG chart prompts
  writeFileSync(join(storyDir, 'visuals.md'), result, 'utf-8');
  console.log(`  ✓ stories/${slug}/visuals.md`);

  // Extract any SVG code blocks into charts.md
  const svgBlocks = [...result.matchAll(/```svg\n([\s\S]*?)```/g)];
  if (svgBlocks.length > 0) {
    const chartsContent = `# Charts for: ${topic}\n\nGenerated by Phase 5 — Visual Assets\n\n` +
      svgBlocks.map((svg, i) => `## Chart ${i + 1}\n\n\`\`\`svg\n${svg[1].trim()}\n\`\`\`\n`).join('\n');
    writeFileSync(join(storyDir, 'charts.md'), chartsContent, 'utf-8');
    console.log(`  ✓ stories/${slug}/charts.md (${svgBlocks.length} SVGs extracted)`);
  }

  console.log('\n  Next: Review visuals.md for image prompts and chart data');
  console.log('        Use: node scripts/ai/website.mjs --slug ' + slug + '\n');
}

main().catch(err => {
  console.error(`\nFatal error: ${err.message}`);
  process.exit(1);
});
