import { CountryProfile } from '@/types'

const COUNTRIES_DATA: CountryProfile[] = [
  {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    capital: 'New Delhi',
    population: 1450000000,
    gdp: 4100000000000,
    gdpGrowth: 6.5,
    inflation: 4.5,
    militarySpending: 75000000000,
    educationIndex: 0.64,
    healthIndex: 0.62,
    aiIndex: 0.74,
    aiRanking: 5,
    militaryRank: 4,
    educationRank: 110,
    healthRank: 120,
    description: 'India is the world\'s most populous country and a fast-growing major economy. With a strong IT services sector, expanding manufacturing base, and ambitious infrastructure programmes, it is emerging as a key player in global affairs. Its demographic dividend, democratic institutions, and strategic location make it a unique power in the Indo-Pacific.',
    topExports: ['Petroleum Products', 'Diamonds & Gems', 'Pharmaceuticals', 'Rice & Cereals', 'IT Services'],
    topImports: ['Crude Oil', 'Gold', 'Electronics', 'Machinery', 'Chemicals'],
    energyMix: [
      { source: 'Coal', percentage: 55 },
      { source: 'Renewable', percentage: 28 },
      { source: 'Hydro', percentage: 8 },
      { source: 'Natural Gas', percentage: 5 },
      { source: 'Nuclear', percentage: 3 },
      { source: 'Oil', percentage: 1 },
    ],
    tradePartners: [
      { country: 'United States', exportValue: 84000000000, importValue: 43000000000 },
      { country: 'China', exportValue: 18000000000, importValue: 95000000000 },
      { country: 'UAE', exportValue: 32000000000, importValue: 21000000000 },
      { country: 'Saudi Arabia', exportValue: 12000000000, importValue: 28000000000 },
      { country: 'Russia', exportValue: 8000000000, importValue: 46000000000 },
    ],
    timeline: [
      { date: '1947', title: 'Independence', description: 'India gains independence from British rule.' },
      { date: '1991', title: 'Economic Liberalisation', description: 'Market reforms open the Indian economy.' },
      { date: '2014', title: 'Modi Government', description: 'BJP-led NDA government assumes office.' },
      { date: '2023', title: 'G20 Presidency', description: 'India hosts G20 Summit in New Delhi.' },
      { date: '2024', title: 'Largest Elections', description: 'India conducts the largest democratic exercise.' },
    ],
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    capital: 'Washington DC',
    population: 340000000,
    gdp: 27400000000000,
    gdpGrowth: 2.5,
    inflation: 3.0,
    militarySpending: 880000000000,
    educationIndex: 0.89,
    healthIndex: 0.84,
    aiIndex: 0.95,
    aiRanking: 1,
    militaryRank: 1,
    educationRank: 15,
    healthRank: 35,
    description: 'The United States remains the world\'s largest economy and foremost military power. It leads in technology, innovation, and artificial intelligence research. Home to Silicon Valley and the world\'s deepest capital markets, the US economy is driven by services, consumption, and technological innovation.',
    topExports: ['Refined Petroleum', 'Crude Oil', 'Aircraft', 'Vehicles', 'Integrated Circuits'],
    topImports: ['Vehicles', 'Crude Oil', 'Computers', 'Broadcasting Equipment', 'Packaged Medicines'],
    energyMix: [
      { source: 'Natural Gas', percentage: 38 },
      { source: 'Oil', percentage: 28 },
      { source: 'Coal', percentage: 12 },
      { source: 'Renewable', percentage: 13 },
      { source: 'Nuclear', percentage: 8 },
      { source: 'Hydro', percentage: 1 },
    ],
    tradePartners: [
      { country: 'China', exportValue: 150000000000, importValue: 540000000000 },
      { country: 'Mexico', exportValue: 320000000000, importValue: 480000000000 },
      { country: 'Canada', exportValue: 350000000000, importValue: 420000000000 },
      { country: 'Japan', exportValue: 80000000000, importValue: 150000000000 },
      { country: 'Germany', exportValue: 75000000000, importValue: 140000000000 },
    ],
    timeline: [
      { date: '1776', title: 'Declaration of Independence', description: 'Thirteen colonies declare independence.' },
      { date: '1945', title: 'Post-War Superpower', description: 'US emerges as a global superpower after WWII.' },
      { date: '1991', title: 'Cold War Victory', description: 'Soviet Union dissolves; US remains sole superpower.' },
      { date: '2008', title: 'Financial Crisis', description: 'Global financial crisis originates in US housing market.' },
      { date: '2024', title: 'Presidential Election', description: 'High-stakes election shapes US domestic and foreign policy.' },
    ],
  },
  {
    code: 'CN',
    name: 'China',
    flag: '🇨🇳',
    capital: 'Beijing',
    population: 1410000000,
    gdp: 18300000000000,
    gdpGrowth: 5.0,
    inflation: 2.0,
    militarySpending: 310000000000,
    educationIndex: 0.72,
    healthIndex: 0.76,
    aiIndex: 0.88,
    aiRanking: 2,
    militaryRank: 2,
    educationRank: 30,
    healthRank: 80,
    description: 'China is the world\'s second-largest economy and a major geopolitical rival to the United States. Its state-led development model has lifted hundreds of millions out of poverty. With ambitious initiatives like the Belt and Road and Made in China 2025, Beijing seeks technological self-sufficiency and global influence.',
    topExports: ['Computers', 'Broadcasting Equipment', 'Integrated Circuits', 'Phones', 'Vehicles'],
    topImports: ['Crude Oil', 'Iron Ore', 'Natural Gas', 'Integrated Circuits', 'Aircraft'],
    energyMix: [
      { source: 'Coal', percentage: 56 },
      { source: 'Renewable', percentage: 20 },
      { source: 'Hydro', percentage: 8 },
      { source: 'Natural Gas', percentage: 7 },
      { source: 'Nuclear', percentage: 5 },
      { source: 'Oil', percentage: 4 },
    ],
    tradePartners: [
      { country: 'United States', exportValue: 540000000000, importValue: 150000000000 },
      { country: 'Japan', exportValue: 180000000000, importValue: 160000000000 },
      { country: 'South Korea', exportValue: 160000000000, importValue: 190000000000 },
      { country: 'Vietnam', exportValue: 140000000000, importValue: 60000000000 },
      { country: 'Germany', exportValue: 120000000000, importValue: 110000000000 },
    ],
    timeline: [
      { date: '1949', title: 'People\'s Republic Founded', description: 'Mao Zedong proclaims the PRC.' },
      { date: '1978', title: 'Reform & Opening Up', description: 'Deng Xiaoping launches market reforms.' },
      { date: '2001', title: 'WTO Accession', description: 'China joins World Trade Organization.' },
      { date: '2013', title: 'Belt & Road Initiative', description: 'Xi Jinping unveils infrastructure megaproject.' },
      { date: '2023', title: 'Xi Consolidates Power', description: 'Third term secured; tightens political control.' },
    ],
  },
  {
    code: 'RU',
    name: 'Russia',
    flag: '🇷🇺',
    capital: 'Moscow',
    population: 144000000,
    gdp: 2100000000000,
    gdpGrowth: 2.5,
    inflation: 6.5,
    militarySpending: 120000000000,
    educationIndex: 0.82,
    healthIndex: 0.70,
    aiIndex: 0.45,
    aiRanking: 12,
    militaryRank: 2,
    educationRank: 45,
    healthRank: 95,
    description: 'Russia is the world\'s largest country by land area and a major energy exporter. Its economy is heavily dependent on oil and gas revenues. A permanent UN Security Council member and nuclear superpower, Russia has asserted its influence through military interventions and energy diplomacy.',
    topExports: ['Crude Oil', 'Natural Gas', 'Refined Petroleum', 'Coal', 'Wheat'],
    topImports: ['Phones', 'Computers', 'Vehicles', 'Packaged Medicines', 'Machinery'],
    energyMix: [
      { source: 'Natural Gas', percentage: 48 },
      { source: 'Oil', percentage: 22 },
      { source: 'Coal', percentage: 15 },
      { source: 'Nuclear', percentage: 8 },
      { source: 'Hydro', percentage: 6 },
      { source: 'Renewable', percentage: 1 },
    ],
    tradePartners: [
      { country: 'China', exportValue: 68000000000, importValue: 76000000000 },
      { country: 'India', exportValue: 46000000000, importValue: 8000000000 },
      { country: 'Turkey', exportValue: 28000000000, importValue: 12000000000 },
      { country: 'Belarus', exportValue: 24000000000, importValue: 15000000000 },
      { country: 'Kazakhstan', exportValue: 18000000000, importValue: 8000000000 },
    ],
    timeline: [
      { date: '1991', title: 'Soviet Dissolution', description: 'USSR collapses; Russian Federation emerges.' },
      { date: '2000', title: 'Putin Era Begins', description: 'Vladimir Putin becomes President.' },
      { date: '2014', title: 'Crimea Annexation', description: 'Russia annexes Crimea from Ukraine.' },
      { date: '2022', title: 'Ukraine Invasion', description: 'Full-scale invasion of Ukraine begins.' },
      { date: '2024', title: 'War Economy', description: 'Economy shifts to wartime production.' },
    ],
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    population: 125000000,
    gdp: 4200000000000,
    gdpGrowth: 1.0,
    inflation: 2.5,
    militarySpending: 50000000000,
    educationIndex: 0.91,
    healthIndex: 0.93,
    aiIndex: 0.62,
    aiRanking: 8,
    militaryRank: 9,
    educationRank: 6,
    healthRank: 2,
    description: 'Japan is the world\'s third-largest economy and a leader in technology, robotics, and automotive manufacturing. Facing demographic challenges from an aging population, Japan has pursued Abenomics-style stimulus, digital transformation, and expanded defence cooperation with allies.',
    topExports: ['Vehicles', 'Integrated Circuits', 'Machinery', 'Steel', 'Optical Instruments'],
    topImports: ['Crude Oil', 'Natural Gas', 'Phones', 'Computers', 'Coal'],
    energyMix: [
      { source: 'Natural Gas', percentage: 32 },
      { source: 'Coal', percentage: 27 },
      { source: 'Oil', percentage: 24 },
      { source: 'Renewable', percentage: 10 },
      { source: 'Nuclear', percentage: 5 },
      { source: 'Hydro', percentage: 2 },
    ],
    tradePartners: [
      { country: 'China', exportValue: 180000000000, importValue: 220000000000 },
      { country: 'United States', exportValue: 150000000000, importValue: 80000000000 },
      { country: 'South Korea', exportValue: 60000000000, importValue: 40000000000 },
      { country: 'Taiwan', exportValue: 50000000000, importValue: 35000000000 },
      { country: 'Australia', exportValue: 20000000000, importValue: 55000000000 },
    ],
    timeline: [
      { date: '1945', title: 'Post-War Reconstruction', description: 'Japan rebuilds after WWII defeat.' },
      { date: '1989', title: 'Bubble Economy Bursts', description: 'Asset price bubble collapses; lost decade begins.' },
      { date: '2011', title: 'Fukushima Disaster', description: 'Earthquake and tsunami cause nuclear meltdown.' },
      { date: '2019', title: 'Reiwa Era Begins', description: 'Emperor Naruhito ascends the throne.' },
      { date: '2024', title: 'Defence Buildup', description: 'Military spending doubles under new security strategy.' },
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    capital: 'London',
    population: 68000000,
    gdp: 3300000000000,
    gdpGrowth: 1.5,
    inflation: 3.5,
    militarySpending: 75000000000,
    educationIndex: 0.93,
    healthIndex: 0.88,
    aiIndex: 0.70,
    aiRanking: 6,
    militaryRank: 8,
    educationRank: 4,
    healthRank: 15,
    description: 'The United Kingdom is a major global economy with a rich history and a leading financial centre in London. Its services sector dominates GDP, and it maintains significant soft power through culture, education, and diplomatic networks. Post-Brexit, the UK is forging new trade deals and asserting Global Britain strategy.',
    topExports: ['Gold', 'Aircraft', 'Vehicles', 'Pharmaceuticals', 'Crude Oil'],
    topImports: ['Gold', 'Vehicles', 'Computers', 'Broadcasting Equipment', 'Packaged Medicines'],
    energyMix: [
      { source: 'Natural Gas', percentage: 38 },
      { source: 'Renewable', percentage: 30 },
      { source: 'Nuclear', percentage: 14 },
      { source: 'Oil', percentage: 10 },
      { source: 'Coal', percentage: 5 },
      { source: 'Hydro', percentage: 3 },
    ],
    tradePartners: [
      { country: 'United States', exportValue: 65000000000, importValue: 55000000000 },
      { country: 'Germany', exportValue: 40000000000, importValue: 70000000000 },
      { country: 'China', exportValue: 25000000000, importValue: 63000000000 },
      { country: 'Netherlands', exportValue: 35000000000, importValue: 45000000000 },
      { country: 'France', exportValue: 30000000000, importValue: 35000000000 },
    ],
    timeline: [
      { date: '1707', title: 'Acts of Union', description: 'Kingdom of Great Britain is formed.' },
      { date: '1945', title: 'Welfare State Founded', description: 'NHS and welfare state established post-WWII.' },
      { date: '1973', title: 'Joins European Economic Community', description: 'UK becomes member of the EEC.' },
      { date: '2016', title: 'Brexit Referendum', description: 'UK votes to leave the European Union.' },
      { date: '2024', title: 'General Election', description: 'Labour returns to power after 14 years.' },
    ],
  },
]

export function getCountryByCode(code: string): CountryProfile | undefined {
  return COUNTRIES_DATA.find(c => c.code === code)
}

export function getAllCountries(): { code: string; name: string }[] {
  return COUNTRIES_DATA.map(c => ({ code: c.code, name: c.name }))
}

export function getAllCountryCodes(): string[] {
  return COUNTRIES_DATA.map(c => c.code)
}
