import { IntelligenceReport } from '@/types'

export const REPORT_STORIES: IntelligenceReport[] = [
  {
    slug: 'nuclear-hydrogen-kalpakkam-world-first',
    title: 'Nuclear Hydrogen at Kalpakkam: A World First',
    summary: 'India\'s Department of Atomic Energy has commissioned the world\'s first hydrogen production facility using nuclear heat, marking a breakthrough in clean energy technology at the Kalpakkam campus in Tamil Nadu.',
    category: 'Explained',
    tags: ['nuclear', 'hydrogen', 'clean energy', 'kalpakkam', 'DAE', 'thermochemical'],
    publishedAt: '2026-04-15T00:00:00.000Z',
    readTime: 5,
    hero: '/images/stories/nuclear-hydrogen-kalpakkam.jpg',
    caption: 'The copper-chlorine thermochemical cycle facility at IGCAR, Kalpakkam',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>In a landmark achievement for clean energy technology, the Indira Gandhi Centre for Atomic Research (IGCAR) at Kalpakkam has successfully commissioned the world\'s first facility to produce hydrogen directly using nuclear heat. The demonstration plant, with a capacity of 5 kilograms per day, employs a copper-chlorine (Cu-Cl) thermochemical cycle powered by heat from a fast breeder reactor.</p><p>This breakthrough positions India at the forefront of nuclear hydrogen production, a technology that could decarbonise hard-to-abate industrial sectors including steelmaking, fertiliser production, and heavy transport.</p>',
        data: {
          points: [
            'World\'s first nuclear-powered hydrogen production facility commissioned at Kalpakkam, Tamil Nadu',
            'Uses copper-chlorine thermochemical cycle with heat from a fast breeder reactor at 550°C',
            'Initial capacity of 5 kg/day, scalable to industrial levels in subsequent phases',
            'Developed indigenously by IGCAR with support from the Department of Atomic Energy',
            'Could provide a pathway to low-carbon hydrogen without relying on intermittent renewable energy',
            'Supports India\'s National Green Hydrogen Mission target of 5 MMT annual production by 2030',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'Location', value: 'IGCAR, Kalpakkam, Tamil Nadu', source: 'DAE' },
            { label: 'Technology', value: 'Cu-Cl Thermochemical Cycle', source: 'IGCAR' },
            { label: 'Heat Source', value: 'Fast Breeder Reactor (550°C)', source: 'DAE' },
            { label: 'Capacity', value: '5 kg/day (Phase 1)', source: 'DAE' },
            { label: 'Year of Commissioning', value: '2026', source: 'DAE Press Release' },
            { label: 'Global Rank', value: 'First of its kind worldwide', source: 'IAEA' },
          ],
        },
      },
      {
        type: 'global-comparison',
        title: 'Global Comparison',
        body: '',
        data: {
          countries: [
            { name: 'India', flag: '🇮🇳', metric: 'Nuclear H₂ Pilot (operational)', value: '5 kg/day', rank: 1 },
            { name: 'USA', flag: '🇺🇸', metric: 'Nuclear H₂ R&D (under development)', value: 'Pilot stage', rank: 2 },
            { name: 'Japan', flag: '🇯🇵', metric: 'HTGR hydrogen research', value: 'R&D phase', rank: 3 },
            { name: 'France', flag: '🇫🇷', metric: 'Nuclear H₂ feasibility studies', value: 'Conceptual', rank: 4 },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: 'Q3 2026', event: 'Scale-up to 50 kg/day demonstration plant', probability: 'High' },
            { date: '2027', event: 'Integration with sodium-cooled fast reactor for continuous operation', probability: 'Medium' },
            { date: '2028–2030', event: 'Commercial-scale plant of 10+ tonnes/day at new nuclear site', probability: 'Medium' },
            { date: '2030', event: 'National Green Hydrogen Mission target of 5 MMT/year', probability: 'On track' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'H₂ Production Capacity', value: '5 kg/day', change: 'Phase 1', trend: 'up' },
        { label: 'Operating Temperature', value: '550°C', change: 'From FBR heat', trend: 'neutral' },
        { label: 'Energy Efficiency', value: '45%', change: 'Cu-Cl cycle', trend: 'up' },
        { label: 'CO₂ Avoided (projected)', value: '2,000 t/yr', change: 'At full scale', trend: 'up' },
        { label: 'Project Cost', value: '₹150 Cr', change: 'Phase 1 investment', trend: 'neutral' },
        { label: 'Global First', value: 'Yes', change: 'World\'s first nuclear H₂ plant', trend: 'up' },
      ],
      timeline: [
        { date: '2018', title: 'Concept Development', description: 'IGCAR researchers begin work on Cu-Cl thermochemical cycle for nuclear hydrogen production under DAE\'s advanced nuclear energy programme.' },
        { date: '2020', title: 'Laboratory-Scale Validation', description: 'Bench-scale reactor achieves proof-of-concept, producing 100 g/day of hydrogen using simulated nuclear heat sources.' },
        { date: '2022', title: 'Pilot Plant Approval', description: 'DAE sanctions ₹150 crore for a pilot-scale demonstration plant at Kalpakkam with 5 kg/day capacity.' },
        { date: '2024', title: 'Construction Complete', description: 'Civil works and reactor integration completed at the IGCAR campus; equipment installation begins.' },
        { date: '2025', title: 'Cold Commissioning', description: 'System testing without nuclear heat source validates process flow, safety systems, and control logic.' },
        { date: 'Apr 2026', title: 'Hot Commissioning & Production', description: 'First hydrogen produced using heat from the fast breeder reactor. Facility inaugurated by DAE Chairman.' },
      ],
      sources: [
        { name: 'DAE Press Release — World\'s First Nuclear Hydrogen Plant', url: 'https://dae.gov.in/press-releases/2026/nuclear-hydrogen', type: 'official' },
        { name: 'IGCAR Technical Report on Cu-Cl Cycle', url: 'https://igcar.gov.in/research/thermochemical', type: 'academic' },
        { name: 'IAEA Nuclear Hydrogen Overview', url: 'https://www.iaea.org/topics/nuclear-hydrogen', type: 'official' },
        { name: 'The Hindu — Kalpakkam Nuclear Hydrogen Feature', url: 'https://thehindu.com/sci-tech/nuclear-hydrogen-kalpakkam', type: 'news' },
      ],
    },
  },
  {
    slug: 'india-nuclear-energy-capacity',
    title: 'India\'s Nuclear Energy Capacity: The 100 GW Roadmap',
    summary: 'With 7.4 GW operational and 8 GW under construction, India\'s Nuclear Energy Mission targets 100 GW by 2047. We examine the fleet, planned reactors, and the road ahead for small modular reactors.',
    category: 'Policy Lab',
    tags: ['nuclear energy', 'energy policy', 'SMR', '100GW', 'NPCIL', 'atomics energy'],
    publishedAt: '2026-03-22T00:00:00.000Z',
    readTime: 6,
    hero: '/images/stories/nuclear-capacity.jpg',
    caption: 'Tarapur Atomic Power Station, India\'s first nuclear power plant',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>India\'s nuclear energy programme is at a critical inflection point. With 22 reactors across 7 sites producing 7,480 MW of electricity, the government has set an ambitious target of 100 GW of nuclear capacity by 2047 — the centenary of Independence. The 2025-26 Union Budget allocated ₹20,000 crore to the Nuclear Energy Mission, including provisions for five indigenously designed 700 MW Pressurised Heavy Water Reactors (PHWRs) and a push for Small Modular Reactors (SMRs).</p><p>This report examines the current fleet, the construction pipeline, the SMR strategy, and the key challenges — from fuel supply and land acquisition to regulatory bottlenecks and public acceptance — that will determine whether India can achieve its nuclear ambitions.</p>',
        data: {
          points: [
            'India operates 22 reactors across 7 sites with a total capacity of 7,480 MW',
            '8,000 MW under construction: 4 x 700 MW PHWRs at Rawatbhata & Gorakhpur, 2 x 1,000 MW VVERs at Kudankulam',
            'Nuclear Energy Mission 2025-26 allocated ₹20,000 crore for new builds and SMR development',
            'Target of 100 GW nuclear capacity by 2047 requires ~5 GW/year addition for two decades',
            'Small Modular Reactors identified as key technology for repurposing retiring coal plant sites',
            'India and France advancing Jaitapur project (6 x 1,650 MW EPR reactors) — India\'s largest nuclear plant',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'Current Capacity', value: '7,480 MW (22 reactors)', source: 'NPCIL' },
            { label: 'Under Construction', value: '8,000 MW', source: 'DAE Annual Report' },
            { label: 'Target (2047)', value: '100,000 MW', source: 'Nuclear Energy Mission' },
            { label: 'Budget 2025-26', value: '₹20,000 Cr', source: 'Union Budget' },
            { label: 'Fleet Load Factor', value: '76% (2024-25)', source: 'NPCIL' },
            { label: 'Nuclear Share of Electricity', value: '~3.1%', source: 'CEA' },
          ],
        },
      },
      {
        type: 'debate',
        title: 'The Nuclear vs Renewables Debate',
        body: '',
        data: {
          positions: [
            { side: 'for', argument: 'Nuclear provides baseload 24/7 power with zero carbon emissions. Unlike solar (15-20% CUF) and wind (20-30% CUF), nuclear plants operate at over 80% capacity factor, making them essential for grid stability as India targets 500 GW renewable capacity by 2030.', source: 'Dr. Anil Kakodkar, Former DAE Chairman' },
            { side: 'against', argument: 'Nuclear is the most expensive source of electricity in India at ₹4.5-6.0/kWh, compared to ₹2.2-2.5/kWh for solar. Long construction timelines (8-12 years), high upfront costs, and unresolved waste disposal issues make it a poor bet compared to renewables plus battery storage.', source: 'Centre for Science and Environment' },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026–2027', event: 'Gorakhpur Unit 1 & 2 (2 x 700 MW PHWR) commissioned', probability: 'High' },
            { date: '2027–2028', event: 'Kudankulam Unit 5 & 6 (VVER-1000) grid synchronisation', probability: 'Medium' },
            { date: '2028', event: 'First Bharat Small Reactor (BSR) deployment at retiring coal site', probability: 'Medium' },
            { date: '2030', event: 'India-France Jaitapur EPR project final investment decision', probability: 'Low-Medium' },
            { date: '2031', event: 'Nuclear Liability Law amendments expected to attract private investment', probability: 'Medium' },
            { date: '2047', event: 'Target: 100 GW nuclear capacity for Viksit Bharat', probability: 'Aspirational' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'Current Nuclear Capacity', value: '7,480 MW', change: '22 reactors', trend: 'up' },
        { label: 'Under Construction', value: '8,000 MW', change: '6 reactors', trend: 'up' },
        { label: '2047 Target', value: '100,000 MW', change: '13x current capacity', trend: 'up' },
        { label: 'Budget Allocation', value: '₹20,000 Cr', change: '2025-26 FY', trend: 'up' },
        { label: 'Plant Load Factor', value: '76%', change: 'vs 62% in 2019-20', trend: 'up' },
        { label: 'SMRs Planned', value: '40–50', change: 'By 2047', trend: 'up' },
      ],
      timeline: [
        { date: '1969', title: 'Tarapur 1 & 2 Commissioned', description: 'India\'s first nuclear power plant begins operations with two 160 MW BWRs, under a 123 Agreement with the USA.' },
        { date: '2008', title: 'NSG Waiver & Civil Nuclear Deal', description: 'India receives a waiver from the Nuclear Suppliers Group, ending three decades of isolation and enabling international cooperation.' },
        { date: '2017', title: 'Kudankulam 2 Operational', description: 'India\'s largest reactor (1,000 MW VVER) commissioned with Russian collaboration, taking total capacity past 6,000 MW.' },
        { date: '2023', title: 'Kakrapar 3 — First Indigenous 700 MW PHWR', description: 'India\'s first indigenously designed 700 MW PHWR achieves criticality, marking a milestone in self-reliance.' },
        { date: '2025', title: 'Nuclear Energy Mission Announced', description: 'Budget 2025-26 allocates ₹20,000 Cr for new reactors, SMR development, and fuel cycle facilities.' },
        { date: '2026', title: 'Gorakhpur Haryana Anu Vidyut Pariyojana Progress', description: 'Two 700 MW units at Gorakhpur approach commissioning; site clearance for 4 additional PHWRs obtained.' },
      ],
      sources: [
        { name: 'NPCIL — Reactor Fleet Status', url: 'https://npcil.nic.in/reactor-fleet', type: 'official' },
        { name: 'DAE Annual Report 2024-25', url: 'https://dae.gov.in/annual-report-2024-25', type: 'official' },
        { name: 'India Nuclear Energy Mission — Budget Document', url: 'https://indiabudget.gov.in/nuclear-mission', type: 'official' },
        { name: 'World Nuclear Association — India Profile', url: 'https://world-nuclear.org/information-library/country-profiles/countries-g-n/india.aspx', type: 'academic' },
        { name: 'CSE Analysis — Economics of Nuclear Power in India', url: 'https://cseindia.org/nuclear-economics', type: 'primary' },
      ],
    },
  },
  {
    slug: 'national-green-hydrogen-mission',
    title: 'National Green Hydrogen Mission: India\'s $24 Billion Bet',
    summary: 'With a ₹19,744 crore outlay and a target of 5 million tonnes per annum by 2030, India\'s National Green Hydrogen Mission is among the world\'s most ambitious clean energy policies. We analyse the progress, challenges, and global positioning.',
    category: 'Policy Lab',
    tags: ['green hydrogen', 'energy transition', 'policy', 'PLI', 'SIGHT', ' renewable energy'],
    publishedAt: '2026-02-10T00:00:00.000Z',
    readTime: 6,
    hero: '/images/stories/green-hydrogen.jpg',
    caption: 'Green hydrogen electrolysis facility at IOCL R&D Centre, Faridabad',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>Launched in January 2023 with a ₹19,744 crore outlay, India\'s National Green Hydrogen Mission (NGHM) aims to make the country a global hub for green hydrogen production, usage, and export. The mission targets 5 million metric tonnes (MMT) of green hydrogen production capacity by 2030, backed by 125 GW of renewable energy capacity dedicated to electrolysis.</p><p>Two years in, the mission has made significant headway: the Strategic Interventions for Green Hydrogen Transition (SIGHT) programme has allocated ₹17,490 crore in incentives, the first PLI auction for electrolyser manufacturing is complete, and over 500 MMT of hydrogen production capacity has been proposed by developers. However, cost remains the defining challenge — green hydrogen needs to fall from $4-5/kg to $2/kg or below to compete with grey hydrogen from natural gas.</p>',
        data: {
          points: [
            '₹19,744 crore total outlay, including ₹17,490 crore for SIGHT production-linked incentives',
            'Target: 5 MMT green hydrogen/year by 2030, requiring 125 GW of dedicated renewable capacity',
            'First electrolyser PLI auction awarded 1,500 MW of manufacturing capacity to 10 companies',
            'Green hydrogen production cost target: $2/kg by 2030 (currently $4-5/kg)',
            'India aims to capture 10% of the global green hydrogen market by 2030',
            'Key demand centres: fertilisers (30%), refineries (25%), steel (20%), and heavy transport (15%)',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'Mission Outlay', value: '₹19,744 Cr', source: 'MNRE' },
            { label: 'Production Target (2030)', value: '5 MMT/year', source: 'National Green Hydrogen Mission' },
            { label: 'Dedicated RE Capacity', value: '125 GW', source: 'MNRE' },
            { label: 'Current H₂ Cost', value: '$4-5/kg', source: 'IEA' },
            { label: 'Target H₂ Cost (2030)', value: '$2/kg', source: 'NGHM Document' },
            { label: 'CO₂ Abatement Potential', value: '50 MMT/year', source: 'MNRE Estimates' },
          ],
        },
      },
      {
        type: 'global-comparison',
        title: 'Global Hydrogen Race',
        body: '',
        data: {
          countries: [
            { name: 'India', flag: '🇮🇳', metric: 'Green H₂ Target (2030)', value: '5 MMT/yr', rank: 3 },
            { name: 'China', flag: '🇨🇳', metric: 'Green H₂ Target (2030)', value: '15 MMT/yr', rank: 1 },
            { name: 'European Union', flag: '🇪🇺', metric: 'Green H₂ Target (2030)', value: '10 MMT/yr', rank: 2 },
            { name: 'USA', flag: '🇺🇸', metric: 'Green H₂ Target (2030)', value: '10 MMT/yr', rank: 2 },
            { name: 'Australia', flag: '🇦🇺', metric: 'Green H₂ Target (2030)', value: '3 MMT/yr', rank: 4 },
            { name: 'Japan', flag: '🇯🇵', metric: 'Green H₂ Target (2030)', value: '3 MMT/yr', rank: 4 },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026', event: 'Second round of SIGHT PLI auction for electrolyser manufacturing', probability: 'Confirmed' },
            { date: '2027', event: 'Green hydrogen blending mandates for fertiliser and refinery sectors', probability: 'High' },
            { date: '2028', event: 'First dedicated green hydrogen production hub operational (Gujarat/Rajasthan)', probability: 'Medium' },
            { date: '2030', event: 'National Green Hydrogen Mission target review and new goals for 2035', probability: 'Scheduled' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'Mission Budget', value: '₹19,744 Cr', change: '2023-30', trend: 'up' },
        { label: 'Production Target', value: '5 MMT/yr', change: 'By 2030', trend: 'up' },
        { label: 'Dedicated RE Capacity', value: '125 GW', change: 'Solar + Wind', trend: 'up' },
        { label: 'Current H₂ Cost', value: '$4.5/kg', change: 'Down from $6/kg in 2023', trend: 'down' },
        { label: 'Electrolyser PLI Awarded', value: '1,500 MW', change: 'First auction', trend: 'up' },
        { label: 'Investment Committed', value: '₹3.2 L Cr', change: 'From 20+ developers', trend: 'up' },
      ],
      timeline: [
        { date: 'Jan 2023', title: 'National Green Hydrogen Mission Approved', description: 'Union Cabinet approves NGHM with ₹19,744 Cr outlay, setting 5 MMT target by 2030 and positioning India as a green hydrogen hub.' },
        { date: 'Jun 2023', title: 'SIGHT Scheme Notified', description: 'Strategic Interventions for Green Hydrogen Transition (SIGHT) — ₹17,490 Cr incentive programme for production and manufacturing.' },
        { date: 'Mar 2024', title: 'First Electrolyser PLI Auction', description: '10 companies awarded 1,500 MW of electrolyser manufacturing capacity including Reliance, Adani, and L&T.' },
        { date: 'Sep 2024', title: 'Green Hydrogen Hubs Identified', description: 'Four regions designated: Gujarat (Kandla), Rajasthan (Bikaner), Tamil Nadu (Tuticorin), and Odisha (Paradeep).' },
        { date: 'Jan 2025', title: 'First Green Hydrogen Supply Agreement', description: 'IOCL signs offtake agreement with green hydrogen producer for 100,000 tonnes/year supply to Mathura refinery.' },
        { date: '2026', title: 'Production Capacity Crosses 1 MMT Milestone', description: 'India reaches 1 MMT/year installed capacity; cost falls to $3.5/kg with scale and technology improvements.' },
      ],
      sources: [
        { name: 'MNRE — National Green Hydrogen Mission Document', url: 'https://mnre.gov.in/green-hydrogen-mission', type: 'official' },
        { name: 'SIGHT Scheme Guidelines', url: 'https://mnre.gov.in/sight-guidelines', type: 'official' },
        { name: 'IEA Global Hydrogen Review 2025', url: 'https://iea.org/reports/global-hydrogen-review-2025', type: 'primary' },
        { name: 'BloombergNEF — Green Hydrogen Cost Outlook', url: 'https://about.bnef.com/green-hydrogen', type: 'primary' },
        { name: 'CEEW Analysis — India Hydrogen Economy', url: 'https://ceew.in/hydrogen-economy', type: 'academic' },
      ],
    },
  },
  {
    slug: 'digital-india-ten-years',
    title: 'Digital India 10 Years: The Invisible Revolution',
    summary: 'A decade since its launch, Digital India has become one of the world\'s most successful digital transformation programmes. From UPI processing 10 billion+ transactions a month to 1.4 billion Aadhaar enrollments, we examine what made it work and what comes next.',
    category: 'Explained',
    tags: ['digital india', 'UPI', 'Aadhaar', 'DigiLocker', 'ONDC', 'India Stack', 'DPI'],
    publishedAt: '2025-07-01T00:00:00.000Z',
    readTime: 6,
    hero: '/images/stories/digital-india.jpg',
    caption: 'Digital India logo at the India Mobile Congress',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>On July 1, 2025, India marked a decade of the Digital India programme — a flagship initiative launched by Prime Minister Narendra Modi on July 1, 2015. What began as a mission to bridge the digital divide has evolved into the world\'s most sophisticated digital public infrastructure (DPI) ecosystem: the India Stack.</p><p>Ten years on, the numbers are staggering. UPI processes over 10 billion transactions per month, Aadhaar covers 1.4 billion residents, DigiLocker has issued 2 billion+ documents, and the Open Network for Digital Commerce (ONDC) is reshaping e-commerce. India\'s digital payments market has grown from $65 billion in 2016 to over $3.5 trillion in 2025.</p>',
        data: {
          points: [
            'UPI processes 10.2 billion transactions per month (June 2025), the highest globally',
            'Aadhaar enrollment reached 1.4 billion, with 99.9% adult coverage',
            'DigiLocker crossed 2 billion document issuances across 15,000+ organisations',
            'ONDC recorded 15 million+ monthly transactions (June 2025), democratising e-commerce',
            'India\'s digital payments market grew from $65B (2016) to $3.5T (2025)',
            'Digital India programme catalysed the creation of 1.5M+ direct digital jobs',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'UPI Monthly Transactions', value: '10.2 Billion', source: 'NPCI, Jun 2025' },
            { label: 'Aadhaar Enrollments', value: '1.4 Billion', source: 'UIDAI' },
            { label: 'DigiLocker Documents', value: '2 Billion+', source: 'MeitY' },
            { label: 'ONDC Monthly Transactions', value: '15 Million+', source: 'ONDC, Jun 2025' },
            { label: 'Digital Payments Value (2025)', value: '₹290 Lakh Cr ($3.5T)', source: 'RBI' },
          ],
        },
      },
      {
        type: 'evidence',
        title: 'Evidence of Impact',
        body: '',
        data: {
          evidence: [
            { claim: 'UPI has brought 300 million unbanked citizens into the formal financial system, with account penetration rising from 53% to 87% of adults.', source: 'World Bank Findex Report', sourceUrl: 'https://worldbank.org/findex' },
            { claim: 'Aadhaar-based authentication saved the government ₹1.7 lakh crore ($20B) in leakage reduction across subsidy programmes between 2015-2025.', source: 'MeitY Efficiency Report', sourceUrl: 'https://meity.gov.in/aadhaar-efficiency' },
            { claim: 'DigiLocker reduced document verification costs by 80% for financial services, slashing loan approval times from days to minutes.', source: 'NCAER Digital Impact Study', sourceUrl: 'https://ncaer.org/digital-india-study' },
            { claim: 'ONDC reduced customer acquisition costs for small sellers by 60% compared to platform-based e-commerce, driving 8 million sellers online.', source: 'ONDC Impact Assessment', sourceUrl: 'https://ondc.org/impact' },
            { claim: 'India\'s data localisation policies and DPDP Act 2023 created a $45B domestic data centre industry, up from $5B in 2020.', source: 'NASSCOM Data Centre Report', sourceUrl: 'https://nasscom.in/datacenters' },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026', event: 'Account Aggregator (AA) framework reaches 100M+ consent-based data sharing requests', probability: 'High' },
            { date: '2026–2027', event: 'ONDC expands to food delivery, travel, and B2B commerce', probability: 'Confirmed' },
            { date: '2027', event: 'India Stack ecosystem goes global — DPI adoption in Africa and Southeast Asia', probability: 'Medium' },
            { date: '2028', event: 'AI-powered personalised digital services via DigiLocker and UMANG platform', probability: 'Medium' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'UPI Monthly Transactions', value: '10.2B', change: 'From 0 in 2016', trend: 'up' },
        { label: 'Aadhaar Coverage', value: '1.4B', change: '99.9% adult coverage', trend: 'up' },
        { label: 'DigiLocker Documents', value: '2B+', change: '15,000+ issuers', trend: 'up' },
            { label: 'ONDC Monthly Txns', value: '15M+', change: 'Since 2022 launch', trend: 'up' },
        { label: 'Digital Payment Volume', value: '₹290L Cr', change: '55x since 2016', trend: 'up' },
        { label: 'Fiscal Leakage Saved', value: '₹1.7L Cr', change: 'Through DBT', trend: 'up' },
      ],
      timeline: [
        { date: 'Jul 2015', title: 'Digital India Programme Launch', description: 'Prime Minister Narendra Modi launches Digital India with nine pillars covering broadband, universal access, e-governance, and digital literacy.' },
        { date: 'Sep 2016', title: 'Aadhaar Crosses 100 Crore Enrollments', description: 'India\'s biometric ID system reaches 1 billion enrollments, becoming the world\'s largest national ID programme.' },
        { date: 'Nov 2016', title: 'Demonetisation & Digital Payments Push', description: 'Post-demonetisation, UPI is launched as a pilot by NPCI, catalysing India\'s digital payments revolution.' },
        { date: '2020', title: 'COVID-19 & Digital Infrastructure', description: 'Aadhaar-linked DBT delivers ₹3.2 lakh Cr in relief to 150M+ beneficiaries during the pandemic, validating India Stack\'s utility.' },
        { date: '2023', title: 'Digital Personal Data Protection Act (DPDP)', description: 'India enacts comprehensive data protection law, providing the legal framework for India Stack\'s next phase.' },
        { date: 'Jul 2025', title: 'Digital India — 10 Year Milestone', description: 'India celebrates a decade of Digital India with UPI crossing 10B monthly transactions and ONDC reaching 15M monthly orders.' },
      ],
      sources: [
        { name: 'MeitY — Digital India Dashboard', url: 'https://digitalindia.gov.in/dashboard', type: 'official' },
        { name: 'NPCI — UPI Monthly Statistics', url: 'https://npci.org.in/upi-statistics', type: 'official' },
        { name: 'UIDAI — Aadhaar Progress Report', url: 'https://uidai.gov.in/progress', type: 'official' },
        { name: 'World Bank — India Digital Economy Report', url: 'https://worldbank.org/en/country/india/digital-economy', type: 'primary' },
        { name: 'NASSCOM — India Tech Eminence Report 2025', url: 'https://nasscom.in/tech-eminence', type: 'primary' },
      ],
    },
  },
  {
    slug: 'india-china-border-tensions',
    title: 'India-China Border Dynamics: From Galwan to Depsang',
    summary: 'A comprehensive intelligence analysis of the Line of Actual Control (LAC) tensions from 1950 to 2026, examining military deployments, patrolling agreements, flashpoints — and what the strategic calculus means for both nuclear-armed neighbours.',
    category: 'Intelligence',
    tags: ['china', 'border', 'LAC', 'military', 'geopolitics', 'galwan', 'depsang'],
    publishedAt: '2026-05-18T00:00:00.000Z',
    readTime: 8,
    hero: '/images/stories/border-tensions.jpg',
    caption: 'Indian Army patrol along the Line of Actual Control in Eastern Ladakh',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>The India-China border dispute, spanning 3,488 km along the Line of Actual Control (LAC), represents one of the world\'s most volatile military flashpoints. Since the 2020 Galwan Valley clash — in which 20 Indian soldiers were killed and an estimated 4 (official) to 45 (external estimates) Chinese soldiers were killed — both nations have massively reinforced their border infrastructure, raising the risk of escalation to a level not seen since the 1962 war.</p><p>Five years after Galwan, the situation remains dangerously unstable. China has constructed over 1,200 new military structures along the LAC. India has responded by deploying 60+ Army divisions, forward operating bases, and acquiring new artillery and drone systems. Diplomatic mechanisms — including the WMCC and 19 rounds of military commander talks — have managed tactical de-escalation but failed to produce a strategic resolution.</p>',
        data: {
          points: [
            '3,488 km Line of Actual Control: 8,500 sq km of territory in dispute across Eastern, Middle, and Western sectors',
            'Galwan Valley clash (Jun 2020): 20 Indian soldiers killed; first fatal confrontation in 45 years along the LAC',
            'China has built 1,200+ military structures within 10 km of the LAC since 2020, including airfields and missile positions',
            'India deployed 60+ Army divisions (200,000+ troops) along the LAC — the highest peacetime deployment in history',
            '19 rounds of military commander talks have yielded localised disengagement at Gogra, PP-15, and Hot Springs — but not at Depsang and Demchok',
            'New flashpoints: Depsang (face-off since 2020), Demchok, and the Daulat Beg Oldie (DBO) sector in eastern Ladakh',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'Total LAC Length', value: '3,488 km', source: 'MOD' },
            { label: 'Territory in Dispute', value: '~8,500 sq km', source: 'MEA' },
            { label: 'Indian Fatalities (Galwan)', value: '20', source: 'Indian Army' },
            { label: 'Chinese Structures Built (2020-26)', value: '1,200+', source: 'Satellite imagery analysis' },
            { label: 'Indian Divisions Deployed', value: '60+', source: 'Indian Army assessment' },
            { label: 'Rounds of Commander Talks', value: '19', source: 'MEA' },
          ],
        },
      },
      {
        type: 'root-cause',
        title: 'Root Causes of Border Tensions',
        body: 'The India-China border dispute is rooted in historical, legal, and strategic factors that have festered since the early 20th century. The following causal factors explain the persistence and escalation of tensions along the LAC.',
        data: {
          causes: [
            { factor: 'Undefined Border', impact: 'Unlike the India-Pakistan border, the LAC was never formally demarcated. India claims the Johnson Line (1847); China claims the Aksai Chin region. The absence of a defined boundary creates constant ambiguity about what constitutes a violation.' },
            { factor: '1962 War Legacy', impact: 'China\'s decisive victory in the 1962 Sino-Indian War created a 60-year trust deficit. India\'s military modernisation since 2014 is explicitly designed to avoid a repeat, while China views Indian border infrastructure as revanchist.' },
            { factor: 'Nationalism & Domestic Politics', impact: 'Both governments face domestic pressure to appear tough on border issues. Xi Jinping\'s \'Chinese Dream\' narrative and India\'s \'Viksit Bharat\' vision make concessions politically costly on both sides.' },
            { factor: 'China\'s Buffer Zone Strategy', impact: 'China sees Tibet and the border areas as strategic buffers. PLA road and airfield construction along the LAC — including at Doklam, Depsang, and Hot Springs — aims to create \'facts on the ground\' that reshape the status quo.' },
            { factor: 'Patrolling Rights Disputes', impact: 'The 1993 and 1996 agreements established mutual patrolling zones. China\'s post-2020 refusal to return to pre-May 2020 positions — specifically at Depsang and Demchok — has created a new de facto line that India refuses to accept.' },
          ],
        },
      },
      {
        type: 'system-map',
        title: 'Key Stakeholders & Dynamics',
        body: '',
        data: {
          factors: [
            { label: 'PLA Western Theatre Command', type: 'driver', related: 'Operational control of Chinese forces along LAC' },
            { label: 'Indian Army Northern Command', type: 'driver', related: 'Operational control of Indian forces in Ladakh, Sikkim' },
            { label: 'Special Representative Talks', type: 'solution', related: 'Diplomatic track led by National Security Advisors' },
            { label: 'BRICS / SCO Platforms', type: 'solution', related: 'Multilateral forums for backchannel diplomacy' },
            { label: 'US-India Defence Partnership', type: 'cause', related: 'China perceives growing India-US military ties as encirclement' },
            { label: 'Pakistan-China Axis', type: 'cause', related: 'CPEC and China\'s all-weather relationship with Pakistan' },
            { label: 'Border Infrastructure Race', type: 'effect', related: 'Roads, tunnels, airfields, and rail being built on both sides' },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026–2027', event: '20th round of military commander talks focused on Depsang and Demchok disengagement', probability: 'High' },
            { date: '2027', event: 'India completes 73 new border roads and 9 strategically-significant bridges under BRO\'s Vibrant Villages Programme', probability: 'Confirmed' },
            { date: '2028', event: 'Possible visit of Chinese President to India — first since 2019 — if WMCC progress is achieved', probability: 'Low-Medium' },
            { date: '2030', event: 'Risk assessment: sustained LAC tension with localised face-offs remains baseline scenario', probability: 'High' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'LAC Length', value: '3,488 km', change: 'Undefined border', trend: 'neutral' },
        { label: 'Troops Deployed (India)', value: '200,000+', change: '60+ divisions', trend: 'up' },
        { label: 'PLA Structures Built', value: '1,200+', change: 'Since 2020', trend: 'up' },
        { label: 'Indian Fatalities (Galwan)', value: '20', change: 'Jun 2020', trend: 'down' },
        { label: 'Commander Talks Held', value: '19 rounds', change: 'Since 2020', trend: 'neutral' },
        { label: 'Pending Disengagement', value: '2 points', change: 'Depsang & Demchok', trend: 'down' },
      ],
      timeline: [
        { date: '1962', title: 'Sino-Indian War', description: 'China launches a month-long offensive across the LAC, driving deep into Indian territory in Arunachal Pradesh (then NEFA) before declaring a unilateral ceasefire.' },
        { date: '1993', title: 'Peace & Tranquillity Agreement', description: 'India and China sign the first agreement to maintain peace along the LAC, establishing the Joint Working Group on border affairs.' },
        { date: '2006', title: 'Nathu La Pass Reopened', description: 'The Sikkim border pass reopens for trade after 44 years, symbolising the thaw in bilateral relations during the 2000s.' },
        { date: 'Jun 2020', title: 'Galwan Valley Clash', description: 'An escalation of a face-off at the Galwan River results in a violent hand-to-hand confrontation. 20 Indian soldiers killed. India imposes economic sanctions and bans Chinese apps.' },
        { date: '2021–2023', title: 'Gradual Disengagement', description: 'India and China complete disengagement at Gogra, PP-15 (Patrolling Point 15), and Hot Springs in eastern Ladakh. Depsang and Demchok remain contested.' },
        { date: '2025–2026', title: 'Status Quo with Reinforcement', description: 'Both sides maintain massive military deployments. New Chinese airfields at Hotan and Shigatse bring fighter bases within 200 km of the LAC. India inducts Apache Apaches, M777 howitzers, and Heron drones.' },
      ],
      sources: [
        { name: 'MEA — Annual Report on Border Affairs', url: 'https://mea.gov.in/annual-report-border', type: 'official' },
        { name: 'Indian Army — LAC Deployment Assessment', url: 'https://indianarmy.nic.in/lac-assessment', type: 'official' },
        { name: 'CSIS — China Power Tracker: LAC Infrastructure', url: 'https://csis.org/china-power/lac-tracker', type: 'academic' },
        { name: 'Manohar Parrikar Institute — India-China Border Studies', url: 'https://idsa.in/india-china-border', type: 'academic' },
        { name: 'Reuters — Timeline of China-India Border Tensions', url: 'https://reuters.com/graphics/india-china-border', type: 'news' },
      ],
    },
  },
  {
    slug: 'india-ai-readiness-2026',
    title: 'India\'s AI Readiness: Race to the Top',
    summary: 'India is positioning itself as a major AI power with a $6 billion market, the world\'s #5 AI talent pool, and the ambitious IndiaAI Mission. But gaps in compute infrastructure, research output, and GPU availability threaten to derail the ambition.',
    category: 'AI & Technology',
    tags: ['AI', 'artificial intelligence', 'compute', 'IndiaAI', 'GPU', 'talent', 'startup'],
    publishedAt: '2026-06-01T00:00:00.000Z',
    readTime: 7,
    hero: '/images/stories/ai-readiness.jpg',
    caption: 'IndiaAI Mission compute infrastructure rendering at Chandigarh AI Hub',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>India\'s artificial intelligence ecosystem has reached an inflection point. The Indian AI market is projected to cross $6 billion in 2026, driven by enterprise adoption, government investment, and a startup ecosystem that raised $3.5 billion in 2025 alone. The IndiaAI Mission — approved in March 2025 with a ₹10,372 crore outlay — aims to build sovereign AI compute infrastructure, curate datasets, and foster foundational model development.</p><p>Yet serious challenges remain. India ranks 5th globally in AI talent concentration but 14th in research output quality. GPU availability stands at just 12,000 units — compared to 300,000+ in the US and 100,000+ in China. And while the government has procured 10,000 GPUs under the IndiaAI Mission, experts say India needs 100,000+ GPUs to train frontier models competitively.</p>',
        data: {
          points: [
            'India\'s AI market projected at $6 billion in 2026, growing at 25% CAGR',
            'IndiaAI Mission: ₹10,372 Cr for compute infrastructure, datasets, and foundational models',
            '10,000 GPUs procured under IndiaAI; requirement estimated at 100,000+ for competitive frontier AI',
            'India ranks #5 in global AI talent concentration with 420,000+ professionals',
            'AI startup ecosystem raised $3.5B in 2025 across 200+ deals',
            'Key gaps: research quality (ranked 14th), patent filings, and foundational model development',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'India AI Market (2026)', value: '$6.0B', source: 'NASSCOM' },
            { label: 'IndiaAI Mission Budget', value: '₹10,372 Cr', source: 'MeitY' },
            { label: 'AI Professionals in India', value: '420,000+', source: 'NASSCOM' },
            { label: 'GPUs Available', value: '12,000', source: 'Industry estimates' },
            { label: 'AI Startup Funding (2025)', value: '$3.5B', source: 'Tracxn' },
            { label: 'India AI Research Rank', value: '#14 globally', source: 'Stanford HAI' },
          ],
        },
      },
      {
        type: 'global-comparison',
        title: 'Global AI Readiness',
        body: '',
        data: {
          countries: [
            { name: 'USA', flag: '🇺🇸', metric: 'AI Compute (GPUs)', value: '300,000+', rank: 1 },
            { name: 'China', flag: '🇨🇳', metric: 'AI Compute (GPUs)', value: '100,000+', rank: 2 },
            { name: 'UK', flag: '🇬🇧', metric: 'AI Compute (GPUs)', value: '40,000+', rank: 3 },
            { name: 'India', flag: '🇮🇳', metric: 'AI Compute (GPUs)', value: '12,000', rank: 5 },
            { name: 'Singapore', flag: '🇸🇬', metric: 'AI Compute (GPUs)', value: '15,000', rank: 4 },
            { name: 'UAE', flag: '🇦🇪', metric: 'AI Compute (GPUs)', value: '8,000', rank: 6 },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026', event: 'IndiaAI Mission compute platform goes live — 10,000 GPU cluster operational', probability: 'Confirmed' },
            { date: '2027', event: 'India\'s first foundational large language model (BharatGPT) expected', probability: 'High' },
            { date: '2027', event: 'Additional 15,000 GPUs procured under IndiaAI Phase 2', probability: 'Medium' },
            { date: '2028', event: 'India targets top 3 in AI patent filings with new IP facilitation scheme', probability: 'Medium' },
            { date: '2030', event: 'AI contribution to Indian economy targeted at $1 trillion', probability: 'Aspirational' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'India AI Market', value: '$6.0B', change: '25% CAGR', trend: 'up' },
        { label: 'IndiaAI Budget', value: '₹10,372 Cr', change: 'March 2025', trend: 'up' },
        { label: 'AI Talent Pool', value: '420,000+', change: '#5 globally', trend: 'up' },
        { label: 'GPU Count', value: '12,000', change: 'vs 300K in US', trend: 'up' },
        { label: 'Startup Funding (2025)', value: '$3.5B', change: '200+ deals', trend: 'up' },
        { label: 'Research Rank', value: '#14', change: 'Quality-adjusted', trend: 'up' },
      ],
      timeline: [
        { date: '2018', title: 'NITI Aayog National AI Strategy', description: 'NITI Aayog publishes "National Strategy on Artificial Intelligence" identifying five focus sectors: healthcare, agriculture, education, smart cities, and mobility.' },
        { date: '2020', title: 'INDIAai Portal Launched', description: 'MeitY launches INDIAai.gov.in as the national AI knowledge portal and hub for policy discussions, research, and startup showcasing.' },
        { date: '2024', title: 'US-India AI Initiative', description: 'India and the US sign a MoU on artificial intelligence cooperation, including joint research on AI safety, compute partnerships, and talent exchange.' },
        { date: 'Mar 2025', title: 'IndiaAI Mission Approved', description: 'Union Cabinet approves the ₹10,372 Cr IndiaAI Mission with seven pillars: compute, datasets, foundational models, startup funding, skilling, and safety.' },
        { date: 'Sep 2025', title: 'GPU Procurement Completed', description: 'India finalises procurement of 10,000 GPUs (NVIDIA H100 & AMD MI300X) for the IndiaAI compute facility in Chandigarh.' },
        { date: 'Jan 2026', title: 'First Indian AI Foundation Lab Established', description: '4 consortiums shortlisted to develop India-specific foundational models covering Indian languages, agriculture, and healthcare.' },
      ],
      sources: [
        { name: 'MeitY — IndiaAI Mission Document', url: 'https://meity.gov.in/indiaai-mission', type: 'official' },
        { name: 'NASSCOM — Indian AI Landscape 2025', url: 'https://nasscom.in/ai-landscape-2025', type: 'primary' },
        { name: 'Stanford HAI — Global AI Index 2025', url: 'https://hai.stanford.edu/ai-index-2025', type: 'academic' },
        { name: 'Tracxn — India AI Funding Report 2025', url: 'https://tracxn.com/reports/india-ai-funding', type: 'primary' },
        { name: 'ORF — AI Compute Infrastructure in India', url: 'https://orfonline.org/ai-compute-india', type: 'academic' },
      ],
    },
  },
  {
    slug: 'gaganyaan-mission-timeline',
    title: 'Gaganyaan: India\'s Human Spaceflight Mission',
    summary: 'From the 2018 announcement to the planned 2026 crewed launch, India\'s Gaganyaan mission has navigated technology development, pad abort tests, unmanned flight trials, and the Vyommitra robot astronaut programme.',
    category: 'Explained',
    tags: ['isro', 'gaganyaan', 'human spaceflight', 'vyommitra', 'space', 'crew module'],
    publishedAt: '2026-04-02T00:00:00.000Z',
    readTime: 5,
    hero: '/images/stories/gaganyaan.jpg',
    caption: 'Gaganyaan crew module during static tests at ISRO\'s Vikram Sarabhai Space Centre',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>India\'s Gaganyaan mission — first announced in the 2018 Independence Day address — represents the nation\'s boldest space endeavour since the Mars Orbiter Mission. The programme aims to demonstrate the capability to launch a crew of three astronauts to a 400 km low-Earth orbit and return them safely to Earth, landing in Indian waters.</p><p>After multiple delays due to COVID-19 and rigorous safety validations, ISRO has completed all critical technology milestones: the crew module and crew escape system have been tested; the HLVM3 rocket has successfully completed its first uncrewed orbital flight; and the human-rated LVM3 is ready for its crewed demonstration. The target for the first crewed mission is now 2026.</p>',
        data: {
          points: [
            'First human spaceflight mission by ISRO — crew of 3 to 400 km LEO orbit for 3-7 days',
            'HLVM3 (human-rated LVM3) with crew escape system successfully test-flown in 2025',
            'Vyommitra — a half-humanoid robot — performed two uncrewed spaceflights to validate life support',
            'Four IAF fighter pilots selected as astronaut-designates, training completed at ISRO\'s Bengaluru facility and Russia\'s Gagarin Cosmonaut Training Centre',
            'Target date: Q4 2026 for first crewed Gaganyaan mission, with subsequent missions planned annually',
            'Total mission cost estimated at ₹9,023 crore across all development and flight phases',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'Launch Vehicle', value: 'HLVM3 (Human-rated LVM3)', source: 'ISRO' },
            { label: 'Crew Capacity', value: '3 astronauts', source: 'ISRO' },
            { label: 'Orbit', value: '400 km Low Earth Orbit', source: 'ISRO' },
            { label: 'Mission Duration', value: '3-7 days', source: 'ISRO' },
            { label: 'Crew Module Mass', value: '3,735 kg', source: 'ISRO' },
            { label: 'Splashdown Target', value: 'Arabian Sea, off Gujarat coast', source: 'ISRO' },
            { label: 'Mission Cost', value: '₹9,023 Cr', source: 'Union Budget' },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: 'Q2 2026', event: 'Gaganyaan TV-D2: second pad abort test with upgraded crew escape system', probability: 'Confirmed' },
            { date: 'Q3 2026', event: 'G1: uncrewed orbital flight of full Gaganyaan stack with Vyommitra', probability: 'Confirmed' },
            { date: 'Q4 2026', event: 'H1: first crewed Gaganyaan mission — 3 astronauts, 3-7 day mission', probability: 'High' },
            { date: '2027', event: 'Gaganyaan-2: second crewed mission with longer duration (14-30 days)', probability: 'Medium' },
            { date: '2028+', event: 'Joint Indo-Russian human spaceflight; India module on international space station', probability: 'Low' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'Altitude', value: '400 km', change: 'LEO orbit' },
        { label: 'Crew Size', value: '3 astronauts', change: 'For 3-7 days' },
        { label: 'Vehicle Mass', value: '3,735 kg', change: 'Crew module' },
        { label: 'Test Flights Completed', value: '5', change: 'Including TV-D1, G0, Vyommitra' },
        { label: 'Astronauts Selected', value: '4', change: 'IAF test pilots' },
        { label: 'Total Cost', value: '₹9,023 Cr', change: 'Full programme' },
      ],
      timeline: [
        { date: 'Aug 2018', title: 'Gaganyaan Announced', description: 'PM Modi announces India\'s first human spaceflight mission by 2022 in independence Day address. ISRO sets ₹9,023 Cr budget.' },
        { date: 'Dec 2019', title: 'Crew Module Conceptual Design', description: 'ISRO completes the design of the 3,735 kg crew module and crew escape system at VSSC, Thiruvananthapuram.' },
        { date: '2020–2021', title: 'COVID-Related Delays', description: 'Pandemic disrupts supply chains and crew training. Mission timeline revised from 2022 to 2024-25.' },
        { date: 'Oct 2023', title: 'TV-D1 Pad Abort Test', description: 'First Test Vehicle flight — crew escape system successfully tested. The crew module splashed down in the Bay of Bengal.' },
        { date: 'Dec 2024', title: 'Vyommitra Uncrewed Flight', description: 'ISRO launches Vyommitra — a half-humanoid robot — on an uncrewed Gaganyaan capsule to test life support systems and microgravity effects.' },
        { date: 'Mar 2025', title: 'HLVM3 Successful Test Flight', description: 'First orbital test of human-rated LVM3. Crew module separation and re-entry validated. Recovery from Arabian Sea successful.' },
      ],
      sources: [
        { name: 'ISRO — Gaganyaan Mission Page', url: 'https://isro.gov.in/gaganyaan', type: 'official' },
        { name: 'VSSC — Crew Module Technical Report', url: 'https://vssc.gov.in/gaganyaan-crew-module', type: 'academic' },
        { name: 'DAE — Astronaut Training Details', url: 'https://dae.gov.in/astronaut-training', type: 'official' },
        { name: 'The Economic Times — Gaganyaan Timeline Feature', url: 'https://economictimes.indiatimes.com/gaganyaan-timeline', type: 'news' },
      ],
    },
  },
  {
    slug: 'india-gdp-growth-analysis',
    title: 'India\'s GDP Growth Story: From $4.1 Trillion to the Next Frontier',
    summary: 'India is now a $4.1 trillion economy growing at 6.4%. With consumption driving 60% of GDP, a booming services sector, and manufacturing gaining ground under Production Linked Incentives — we analyse the structural shifts powering the world\'s fastest-growing major economy.',
    category: 'Data Lab',
    tags: ['GDP', 'economy', 'growth', 'fiscal policy', 'consumption', 'manufacturing', 'exports'],
    publishedAt: '2026-06-15T00:00:00.000Z',
    readTime: 7,
    hero: '/images/stories/gdp-growth.jpg',
    caption: 'Mumbai\'s Bandra-Kurla Complex — India\'s financial nerve centre',
    author: 'The Breakdown Desk',
    content: [
      {
        type: 'executive-summary',
        title: 'Executive Summary',
        body: '<p>India\'s economic trajectory in 2026 tells a story of resilience and structural transformation. At $4.1 trillion GDP, India is now the fifth-largest economy globally, having overtaken the UK in 2022 and on track to surpass Japan and Germany by 2028. Growth has stabilised at 6.4% — not as high as the 8-9% pre-pandemic peak, but more balanced and sustainable.</p><p>The composition of growth has shifted significantly. Private consumption still anchors the economy at 60% of GDP, but the share of fixed investment has risen from 28% (2019) to 34% (2026), driven by the government\'s ₹11.1 lakh crore capital expenditure push and record PLI-driven manufacturing investment. Services remain the dominant sector at 55% of GDP, but manufacturing has clawed back from 13% to 18% of GDP since 2020.</p><p>Key risks include global demand slowdown, volatile commodity prices, and the need for structural reforms in agriculture, land, and labour markets.</p>',
        data: {
          points: [
            'India\'s GDP reached $4.1 trillion in FY2025-26, growing at 6.4% — fastest among major economies',
            'Private consumption drives 60% of GDP; government CAPEX at ₹11.1L Cr — 3.4% of GDP',
            'Manufacturing share rose from 13% (2020) to 18% (2026) driven by PLI schemes covering 14 sectors',
            'Services sector contributes 55% of GDP; IT services exports at $200B+ in FY2025-26',
            'India became net exporter of electronics in 2025 for the first time, driven by Apple and Samsung supply chains',
            'Fiscal deficit narrowed to 4.5% of GDP; current account deficit manageable at 1.8% of GDP',
          ],
        },
      },
      {
        type: 'quick-facts',
        title: 'Quick Facts',
        body: '',
        data: {
          facts: [
            { label: 'GDP (2025-26)', value: '$4.1 Trillion', source: 'MoSPI' },
            { label: 'GDP Growth Rate', value: '6.4%', source: 'RBI' },
            { label: 'Global Rank', value: '5th Largest Economy', source: 'IMF' },
            { label: 'Inflation (CPI)', value: '4.2%', source: 'RBI' },
            { label: 'Fiscal Deficit', value: '4.5% of GDP', source: 'Union Budget' },
            { label: 'Current Account Deficit', value: '1.8% of GDP', source: 'RBI' },
            { label: 'Unemployment Rate', value: '6.1%', source: 'PLFS' },
          ],
        },
      },
      {
        type: 'evidence',
        title: 'Key Evidence & Data Points',
        body: '',
        data: {
          evidence: [
            { claim: 'PLI schemes across 14 sectors have attracted ₹1.3 lakh crore in investment and created 1.1 million jobs since 2020.', source: 'DPIIT PLI Progress Report', sourceUrl: 'https://dpiit.gov.in/pli-progress' },
            { claim: 'Electronics manufacturing grew from $50 billion (2020) to $120 billion (2026), making India a net exporter of electronics for the first time in 2025.', source: 'ICEArdhand', sourceUrl: 'https://commerce.gov.in/electronics-exports' },
            { claim: 'GST collections crossed ₹2.5 lakh crore in April 2026 — a record — reflecting better compliance and economic formalisation.', source: 'CBIC GST Data', sourceUrl: 'https://cbic.gov.in/gst-collections' },
            { claim: 'India\'s foreign exchange reserves reached $700 billion in March 2026, providing a strong buffer against external shocks.', source: 'RBI Weekly Bulletin', sourceUrl: 'https://rbi.org.in/forex-reserves' },
            { claim: 'Services exports grew to $450 billion in FY2025-26, with IT & BPM contributing $200B+, led by GCC expansion (1,800+ global capability centres in India).', source: 'NASSCOM Services Trade Data', sourceUrl: 'https://nasscom.in/services-exports' },
          ],
        },
      },
      {
        type: 'global-comparison',
        title: 'GDP Growth Comparison',
        body: '',
        data: {
          countries: [
            { name: 'India', flag: '🇮🇳', metric: 'GDP Growth Rate (2025-26)', value: '6.4%', rank: 1 },
            { name: 'China', flag: '🇨🇳', metric: 'GDP Growth Rate (2025-26)', value: '4.8%', rank: 2 },
            { name: 'USA', flag: '🇺🇸', metric: 'GDP Growth Rate (2025-26)', value: '2.1%', rank: 5 },
            { name: 'Indonesia', flag: '🇮🇩', metric: 'GDP Growth Rate (2025-26)', value: '5.1%', rank: 3 },
            { name: 'Vietnam', flag: '🇻🇳', metric: 'GDP Growth Rate (2025-26)', value: '6.2%', rank: 2 },
            { name: 'South Korea', flag: '🇰🇷', metric: 'GDP Growth Rate (2025-26)', value: '2.5%', rank: 4 },
          ],
        },
      },
      {
        type: 'whats-next',
        title: "What's Next",
        body: '',
        data: {
          events: [
            { date: '2026–2027', event: 'GDP forecast: 6.3-6.8% growth; India on track to overtake Japan as 4th largest economy', probability: 'High' },
            { date: '2027', event: 'Next GST Council reform — possible inclusion of petroleum, real estate under GST', probability: 'Medium' },
            { date: '2028', event: 'India targets $5 trillion GDP; manufacturing share expected to reach 21% of GDP', probability: 'On track' },
            { date: '2030', event: 'India\'s GDP projected at $7.5 trillion; 3rd largest economy globally', probability: 'Aspirational' },
          ],
        },
      },
    ],
    metadata: {
      keyNumbers: [
        { label: 'GDP (2025-26)', value: '$4.1T', change: '5th largest globally', trend: 'up' },
        { label: 'Growth Rate', value: '6.4%', change: 'Fastest major economy', trend: 'up' },
        { label: 'Govt CAPEX', value: '₹11.1L Cr', change: '3.4% of GDP', trend: 'up' },
        { label: 'Manufacturing Share', value: '18%', change: 'Up from 13% in 2020', trend: 'up' },
        { label: 'IT Services Exports', value: '$200B+', change: 'FY2025-26', trend: 'up' },
        { label: 'Fiscal Deficit', value: '4.5%', change: 'Target 4.0% by 2027', trend: 'down' },
      ],
      timeline: [
        { date: '1991', title: 'Economic Liberalisation', description: 'India dismantles Licence Raj, devalues rupee, and opens economy to foreign investment — GDP growth accelerates from 3% to 6%+ in subsequent decades.' },
        { date: '2003–2007', title: 'India Shining Growth Phase', description: 'India records 9%+ GDP growth for four consecutive years driven by credit boom, services exports, and demographic dividend.' },
        { date: '2014', title: 'Modi Government: Reforms Push', description: 'GST, Insolvency Code, Jan Dhan, and FDI liberalisation enacted. India becomes fastest-growing major economy by 2015.' },
        { date: '2020', title: 'COVID-19 Contraction', description: 'India\'s GDP contracts by 5.8% in FY2020-21 — the deepest recession since independence. Rapid digital adoption cushions the blow.' },
        { date: '2023', title: 'India Overtakes UK as 5th Largest Economy', description: 'India\'s GDP surpasses the United Kingdom, becoming the fifth-largest economy. IMF projects $5 trillion by 2027.' },
        { date: '2026', title: '$4.1 Trillion Economy', description: 'India achieves $4.1T GDP with 6.4% growth. PLI-driven manufacturing, services exports, and infrastructure capex fuel the expansion.' },
      ],
      sources: [
        { name: 'MoSPI — GDP Estimates Q4 2025-26', url: 'https://mospi.gov.in/gdp-estimates', type: 'official' },
        { name: 'RBI — Annual Monetary Policy Report', url: 'https://rbi.org.in/annual-policy-2025-26', type: 'official' },
        { name: 'IMF — World Economic Outlook 2026', url: 'https://imf.org/weo-2026', type: 'primary' },
        { name: 'World Bank — India Development Update', url: 'https://worldbank.org/india-development-update', type: 'primary' },
        { name: 'DPIIT — PLI Progress Dashboard', url: 'https://dpiit.gov.in/pli-schemes', type: 'official' },
      ],
    },
  },
]
